### PR TITLE
The license file is named incorrectly, let's fix it

### PR DESCRIPTION
**Pull request by logicalhan**

### CODE REVIEW

**Comment by logicalhan** [comment]
The other license files are also misnamed but those look a bit more hairy to fix.

**Comment by avestuk** [comment]
Hi @logicalhan thanks for the PR. We're using the UK spelling of `licence` so I'm afraid we have diametrically opposing views as to which spelling is correct. Unless there's some other reason, aside from spelling, to change the name we'd want to leave it as is.

**Comment by logicalhan** [comment]
Ah I didn't realize, feel free to close this. 

(FYI the text in the actual license spells it with an 's' as well.)

**Comment by avestuk** [comment]
Thanks for pointing that out. I'll take a look!

**Pull request closed without merging**
